require('dotenv').config()
const express = require('express')
const bodyParser = require('body-parser')
const cors = require('cors')
const connectDB = require('./config/mongo')
const companyRoutes = require('./routes/companyRoutes')
const app = express()
app.use(cors())
app.use(bodyParser.json())
app.use('/api/company', companyRoutes)
const PORT = process.env.PORT || 5000
connectDB().then(() => { app.listen(PORT, () => console.log('Server listening on', PORT)) }).catch(err => console.error(err))